steps:
  - id: 'download-sourcegraph'
    name: 'gcr.io/cloud-builders/curl'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        set -euxo pipefail &&
        mkdir sourcegraph &&
        curl -L https://github.com/sourcegraph/sourcegraph/archive/${_COMMIT_SHA}.tar.gz | tar xz -C sourcegraph --strip-components 1

  - id: 'docker-build'
    name: 'gcr.io/kaniko-project/executor:latest'
    dir: 'sourcegraph'
    args:
      - '--dockerfile=cmd/symbols/Dockerfile'
      - '--destination=${_IMAGE}'
      - '--context=dir://.'

      - '--cache=true'
      - '--cache-ttl=6h'

      - '--build-arg'
      - 'COMMIT_SHA=${_COMMIT_SHA}'

      - '--build-arg'
      - 'DATE=${_DATE}'

      - '--build-arg'
      - 'VERSION=${_VERSION}'

      - '--build-arg'
      - 'CTAGS_VERSION=${_CTAGS_VERSION}'

      - '--build-arg'
      - 'BUILD_TYPE=${_BUILD_TYPE}'
tags:
  - 'symbols'
  - '${_COMMIT_SHA}'
timeout: 1200s
substitutions:
  '_IMAGE': 'us.gcr.io/sourcegraph-dev/symbols:latest'
  '_COMMIT_SHA': 'unknown'
  '_DATE': 'unknown'
  '_VERSION': 'unknown'
  '_CTAGS_VERSION': '03f933a96d3ef87adbf9d167462d45ce69577edb'
  '_BUILD_TYPE': 'dist'
