# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/beevik/etree"

[[constraint]]
  name = "github.com/boj/redistore"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/coocood/freecache"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/go-oidc"

[[constraint]]
  name = "github.com/crewjam/saml"
  version = "0.2.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/dlclark/regexp2"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/felixfbecker/stringscore"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/gobwas/glob"

[[constraint]]
  branch = "master"
  name = "github.com/google/zoekt"
  source = "github.com/sourcegraph/zoekt"

[[constraint]]
  branch = "master"
  name = "github.com/hjr265/redsync.go"

[[constraint]]
  name = "github.com/juju/ratelimit"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/keegancsmith/sqlhooks"

[[constraint]]
  branch = "master"
  name = "github.com/keegancsmith/tmpfriend"

[[constraint]]
  branch = "master"
  name = "github.com/kr/text"

[[constraint]]
  branch = "master"
  name = "github.com/neelance/parallel"

[[constraint]]
  name = "github.com/opentracing/basictracer-go"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/github_flavored_markdown"

[[constraint]]
  branch = "master"
  name = "github.com/sourcegraph/go-vcsurl"

[[constraint]]
  branch = "master"
  name = "github.com/sourcegraph/gosyntect"

[[constraint]]
  branch = "master"
  name = "github.com/sourcegraph/httpcache"

[[constraint]]
  branch = "master"
  name = "github.com/sourcegraph/jsonx"

[[constraint]]
  name = "gopkg.in/inconshreveable/log15.v2"
  version = "2.11.0"

[[constraint]]
  branch = "master"
  name = "gopkg.in/jpoehls/gophermail.v0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "2.0.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
