# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

# Dev tools not directly imported
required = [
  "honnef.co/go/tools/cmd/staticcheck",
  "github.com/jteeuwen/go-bindata/go-bindata",
  "github.com/mattn/goreman",
  "github.com/sourcegraph/godockerize",
  "github.com/sqs/generate/cmd/schema-generate",
  "golang.org/x/tools/cmd/stringer"
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

# The latest release (v3.0.7) doesn't include the -nometadata which we use.
[[constraint]]
  branch = "master"
  name = "github.com/jteeuwen/go-bindata"

# We don't support the godef code that is in master of go-langserver
[[constraint]]
  name = "github.com/sourcegraph/go-langserver"
  revision = "d62c2787506ccc8d2cf68eae5a892ca7130e2cbb"

[[constraint]]
  branch = "master"
  name = "github.com/beevik/etree"

[[constraint]]
  name = "github.com/boj/redistore"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/coocood/freecache"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/go-oidc"

[[constraint]]
  branch = "master"
  name = "github.com/crewjam/saml"
  source = "github.com/beyang/saml"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/dlclark/regexp2"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/felixfbecker/stringscore"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/gobwas/glob"

[[constraint]]
  branch = "master"
  name = "github.com/google/zoekt"
  source = "github.com/sourcegraph/zoekt"

[[constraint]]
  branch = "master"
  name = "github.com/hjr265/redsync.go"

[[constraint]]
  name = "github.com/juju/ratelimit"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/keegancsmith/sqlhooks"

[[constraint]]
  branch = "master"
  name = "github.com/keegancsmith/tmpfriend"

[[constraint]]
  branch = "master"
  name = "github.com/kr/text"

[[constraint]]
  branch = "master"
  name = "github.com/neelance/parallel"

[[constraint]]
  name = "github.com/opentracing/basictracer-go"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/github_flavored_markdown"

[[constraint]]
  branch = "master"
  name = "github.com/sourcegraph/go-vcsurl"

[[constraint]]
  branch = "master"
  name = "github.com/sourcegraph/gosyntect"

[[constraint]]
  branch = "master"
  name = "github.com/sourcegraph/httpcache"

[[constraint]]
  branch = "master"
  name = "github.com/sourcegraph/jsonx"

[[constraint]]
  name = "gopkg.in/inconshreveable/log15.v2"
  version = "2.11.0"

[[constraint]]
  branch = "master"
  name = "gopkg.in/jpoehls/gophermail.v0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

# pinned for k8s.io/client-go@v6.0.0
[[constraint]]
  name = "k8s.io/api"
  revision = "11147472b7c934c474a2c484af3c0c5210b7a3af"

# pinned for k8s.io/client-go@v6.0.0
[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "180eddb345a5be3a157cea1c624700ad5bd27b8f"

# pinned for k8s.io/client-go@v6.0.0
[[override]]
  name = "github.com/golang/protobuf"
  revision = "1643683e1b54a9e88ad26d98f81400c8c9d9f4f9"

# pinned for k8s.io/client-go@v6.0.0
[[override]]
  name = "github.com/gogo/protobuf"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"

[[constraint]]
  name = "github.com/mattn/goreman"
  version = "0.0.10"
