env:
  ENTERPRISE: "1"
  DOCKER_BUILDKIT: "1"
  ENTERPRISE: "1"
  FORCE_COLOR: "3"
  GO111MODULE: "on"
  IMAGE: us.gcr.io/sourcegraph-dev/server:$TAG
  TEST_USER_PASSWORD: "SuperSecurePassword"

steps:
- command:
  # todo: needed?
  - yes | gcloud auth configure-docker
  - pushd enterprise
  - ./cmd/server/pre-build.sh
  - ./cmd/server/build.sh
  - popd
  - ./dev/ci/e2e.sh
  env:
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  label: ':docker::chromium:'
  artifact_paths: ./puppeteer/*.png;./web/e2e.mp4;./web/ffmpeg.log
  agents:
    queue: e2e
