languageCode = "en-us"
title = "Documentation"
layoutDir = "docs/.layouts"
contentDir = "docs"

[params]
SectionOrder = [
	"getting-started",
	"install",
	"config",
	"features",
	"integrations",
	"management",
	"dev",
	"troubleshooting"
]

[params.SectionNames]
install = "Installation"
config = "Configuration"
features = "Features"
integrations = "Integrations"
management = "Management"
dev = "Development"
