groups:
  - name: frontend
    rules:
      - record: alert_count
        labels:
          container: frontend
          level: critical
        expr: 0
      - record: alert_count
        labels:
          container: frontend
          level: warning
        expr: 0
