groups:
  - name: gitserver
    rules:
      - record: alert_count
        labels:
          container: gitserver
          level: critical
        expr: 0
      - record: alert_count
        labels:
          container: gitserver
          level: warning
        expr: 0
