groups:
  - name: lsif-server
    rules:
      - record: alert_count
        labels:
          container: lsif-server
          level: critical
        expr: 0
      - record: alert_count
        labels:
          container: lsif-server
          level: warning
        expr: 0
