groups:
  - name: query-runner
    rules:
      - record: alert_count
        labels:
          container: query-runner
          level: critical
        expr: 0
      - record: alert_count
        labels:
          container: query-runner
          level: warning
        expr: 0
