groups:
  - name: replacer
    rules:
      - record: alert_count
        labels:
          container: replacer
          level: critical
        expr: 0
      - record: alert_count
        labels:
          container: replacer
          level: warning
        expr: 0
