groups:
  - name: repo-updater
    rules:
      - record: alert_count
        labels:
          service_name: repo-updater
          level: critical
        expr: 0
      - record: alert_count
        labels:
          service_name: repo-updater
          level: warning
        expr: 0
