groups:
  - name: searcher
    rules:
      - record: alert_count
        labels:
          container: searcher
          level: critical
        expr: 0
      - record: alert_count
        labels:
          container: searcher
          level: warning
        expr: 0
