groups:
  - name: symbols
    rules:
      - record: alert_count
        labels:
          service_name: symbols
          level: critical
        expr: 0
      - record: alert_count
        labels:
          service_name: symbols
          level: warning
        expr: 0
