groups:
  - name: symbols
    rules:
      - record: alert_count
        labels:
          container: symbols
          level: critical
        expr: 0
      - record: alert_count
        labels:
          container: symbols
          level: warning
        expr: 0
