groups:
  - name: zoekt-webserver
    rules:
      - record: alert_count
        labels:
          container: zoekt-webserver
          level: critical
        expr: 0
      - record: alert_count
        labels:
          container: zoekt-webserver
          level: warning
        expr: 0
