groups:
  - name: zoekt-indexserver
    rules:
      - record: alert_count
        labels:
          container: zoekt-indexserver
          level: critical
        expr: 0
      - record: alert_count
        labels:
          container: zoekt-indexserver
          level: warning
        expr: 0
