name: LSIF
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: asdf_install
        uses: asdf-vm/actions/install@v1.0.0
        with:
          before_install: "bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring"
      - name: Install GNU parallel
        run: sudo apt-get install parallel
      - name: "dev/check/all.sh"
        run: dev/check/all.sh
